[tox]
envlist = flake8, py{37,38,39,310,311,312,313}

[testenv]
passenv = TRAVIS,TRAVIS_JOB_ID,TRAVIS_BRANCH
deps =
  pytest
  coveralls
  setuptools
  mock
  python-dateutil>=2.8.0
  PyYAML
  # for python 3.4
  typing
commands =
	coverage run --source=pyhocon -m pytest tests
	coverage report -m

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 pyhocon tests setup.py
