[tox]
envlist = flake8, py{38,39,310,311,312,313,314}

[testenv]
passenv =
    TRAVIS
    TRAVIS_JOB_ID
    TRAVIS_BRANCH
deps =
  pytest
  coveralls
  python-dateutil>=2.8.0
  # for python 3.4
  typing
commands =
	coverage run --source=pyhocon setup.py test
	coverage report -m
	coveralls

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 --extend-ignore=E1,W1 --max-line-length=128 --exclude=.tox,site-packages,dist,build,*.egg-info,*.egg,docs
